### ISSUE TITLE
If using session tokens, assumed role cred duration can only be max 1 hour

### ISSUE THREAD

**Issue by mmmorris1975** [mmmorris1975/aws-runas#11]
Even though AWS now allows Assume Role credentials to last longer than 1 hour, trying to get them using session token credentials still caps that at 1 hour.  Trying to do more than 1 hour results in this error:

```
Error doing AssumeRole: ValidationError: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
```

Need to adjust this behavior so that Assume Role credentials can last longer

**Comment by mmmorris1975** [comment]
Fixed as part of 1.0.0-beta3

**Comment by iZervy** [comment]
Can you share how do you fix this?
I also have this error because of role chaining.

**Comment by mmmorris1975** [comment]
Since this is a hard limitation on the AWS end, we're working around this in code.  The "usual" behavior for aws-runas is to obtain session token credentials (which will satisfy any mfa requirements for the session token lifetime, instead of the much shorter assume role credentials).  And this still works with the "default" role settings of 1 hour credentials when doing an assume role operation.

In this case, aws-runas logic was modified such that a request for assume role credentials lasting longer than 1 hour would do the AssumeRole operation directly (bypassing the use of session token credentials), and caching those credentials instead.  The thought being that the maximum role credential duration would be some value much larger than 1 hour (4-12 hours), and the burden of having to re-enter any mfa code (if required) would be lessened to a tolerable degree.

Hope that helps, and if you're seeing any behavior that's different than what I described, feel free to post more information on the problem and it can be investigated.  (I obviously won't be able to assume any of your roles, but I can probably get a general idea of what you're trying to do, and attempt to duplicate in my own setup)
