### ISSUE TITLE
Aliases are not recognized

### ISSUE THREAD

**Issue by pearsontophergopher** [mmmorris1975/aws-runas#16]
I have the following alias in my rc file: `alias k='kubectl'`. I am able to run `k get nodes` and have that command work.
Unfortunately, when I try to use that with aws-runas, I get the following result:
```
aws-runas qa k --context=tds -v=4 get nodes                            130 ↵  10007  09:41:55
aws-runas.main 2018/07/03 09:42:00 [CRIT] ▶ exec: "k": executable file not found in $PATH
```

I'm guessing that there is some sort of internal check that maybe doesn't recognize/expand bash aliases?
My workaround is that I just don't use the alias, so no big deal, just thought a it was worthy of a bug report. :-)

**Comment by mmmorris1975** [comment]
This behavior is by design.  The underlying call out to the command is performed by Golang's `os/exec` module, which doesn't use a shell to execute commands, but calls the command directly (a la Python or C's execvp() call)

I'm not opposed to an alternate implementation which is shell aware, however it would need to be something that is also shell-agnostic and compatible across platforms, since the command needs to work across linux, mac and windows platforms.

**Comment by pearsontophergopher** [comment]
That's fair - 
How would you feel about [something like this](https://github.com/codeskyblue/go-sh) as an alternative?
It looks like under the covers, they are still using os/exec, so it looks* like it might be cross compatible.
If it's not cross-compatible though, I withdraw my issue :-)

**Comment by mmmorris1975** [comment]
I gave that `go-sh` library a run, and it looks like it's not inheriting aliases from the caller, only using aliases defined in the code.  I whipped up this quick test case:
```
package main
  
import "github.com/codeskyblue/go-sh"
import "fmt"
import "os/exec"

func main() {
        fmt.Println("** Running Command 'ls -l'")
        if err := sh.Command("ls", "-l").Run(); err != nil {
                fmt.Printf("ERROR: %v\n", err)
        }
        print("\n")

        fmt.Println("** Setting go-sh alias")
        s := sh.NewSession()
        s.Alias("ll", "ls", "-l")
        if err := s.Command("ll").Run(); err != nil {
                fmt.Printf("ERROR: %v\n", err)
        }
        print("\n")

        fmt.Println("** Trying bare shell alias")
        if err := sh.Command("ll").Run(); err != nil {
                fmt.Printf("ERROR: %v\n", err)
        }
        print("\n")

        fmt.Println("** Using sub-shell exec()")
        out, err := exec.Command("bash", "-i", "-c", "ll").Output()
        if err != nil {
                fmt.Printf("ERROR: %v\n", err)
        }
        fmt.Printf("%s\n", out)
}
```

And got these results:
```
** Running Command 'ls -l'
total 6512
-rw-r--r--  1 morrm1  staff      757 Jul  7 12:58 main.go
-rwxr-xr-x  1 morrm1  staff  3329648 Jul  7 12:58 x

** Setting go-sh alias
total 6512
-rw-r--r--  1 morrm1  staff      757 Jul  7 12:58 main.go
-rwxr-xr-x  1 morrm1  staff  3329648 Jul  7 12:58 x

** Trying bare shell alias
ERROR: exec: "ll": executable file not found in $PATH

** Using sub-shell exec()
total 6512
-rw-r--r--  1 morrm1  staff      757 Jul  7 12:58 main.go
-rwxr-xr-x  1 morrm1  staff  3329648 Jul  7 12:58 x
```

A possible solution will be kind of hacky, but before the call to exec the command is made, we could do something like:

1. Check if running on a non-windows platform
2. A call to exec.LookPath() for the desired command fails (no binary command found)
3. The SHELL env var is set
4. Based on the value set for $SHELL, wrap the command (alias) in the necessary stuff to execute via a sub shell (ex `bash -i -c ...`)

Step 4 would have to be customized for each shell that would support this feature (to get the args right), but bash would be the logical 1st choice.

**Comment by mmmorris1975** [comment]
A somewhat germane discussion on the topic:
https://groups.google.com/forum/#!topic/golang-nuts/C8-wqxzr1PI

**Comment by mmmorris1975** [comment]
What do you think about this?  6ed4ba66

**Comment by pearsontophergopher** [comment]
Thank you for giving that library a shot.
I know you didn't ultimately want to write any OS specific code, but https://github.com/mmmorris1975/aws-runas/commit/6ed4ba664e81723939e843543504f9c35540c586 would be an awesome addition imho.

**Comment by mmmorris1975** [comment]
Fixed in [1.0.2](https://github.com/mmmorris1975/aws-runas/releases/tag/1.0.2)

**Comment by mmmorris1975** [comment]
I fixed some goofy behavior where you'd need to quote the command supplied to aws-runas if you were using a shell alias.  The 1.1.0-beta release should make using aliases a bit more "natural", you can download it here: https://github.com/mmmorris1975/aws-runas/releases/tag/1.1.0-beta

**Comment by mmmorris1975** [comment]
Calling this "official" as part of release 1.1.0

**Comment by sjas** [comment]
workaround: https://stackoverflow.com/a/79923180/805284
