### ISSUE TITLE
Difference in behaviour when using AWS_PROFILE

### ISSUE THREAD

**Issue by stephencoe** [mmmorris1975/aws-runas#27]
Hey @mmmorris1975 👋 

I was testing the recent version of the cli (previously on `1.0.0`) and it appears that using `AWS_PROFILE` throws `SIGSEGV` error 

```
$ AWS_PROFILE=sandbox aws-runas -v -D
aws-runas.main 2018/10/12 08:53:31 [DEBU] ▶ PROFILE: sandbox
Assume Role MFA token code: 123456
aws-runas.main 2018/10/12 08:53:39 [WARN] ▶ Error getting IAM user info, retrying with AWS credential env vars unset
Assume Role MFA token code: 987654
aws-runas.main 2018/10/12 08:53:56 [WARN] ▶ Error getting IAM user info: ValidationError: Must specify userName when calling with non-User credentials
	status code: 400, request id: fc9b1914-cdf3-11e8-b8d6-a7951e68fc2c
aws-runas.main 2018/10/12 08:53:56 [DEBU] ▶ Diagnostics
SharedCfgConfigHandler 2018/10/12 08:53:56 [DEBU] ▶ Section 'sandbox' not found, trying 'profile sandbox'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1491c32]

goroutine 1 [running]:
main.awsProfile(0x166e280, 0xc4200a16a0, 0xc4200221ac, 0x7, 0x0, 0x0, 0xc4200b6101, 0xc4200b6178)
	/Users/morrm1/go/src/github.com/mmmorris1975/aws-runas/main.go:384 +0x2d2
main.main()
	/Users/morrm1/go/src/github.com/mmmorris1975/aws-runas/main.go:163 +0x1057

```

When using the tool the other way, defining the profile after the command `aws-runas sandbox` I successfully get an auth token

**Comment by mmmorris1975** [comment]
I think I found what's causing this.  The AWS SDK is picking up that environment variable when the tool is making a call to IAM to get info for the calling user.  I have a fix you can try in a version you can download here: https://github.com/mmmorris1975/aws-runas/releases/tag/c8394d3

Let me know how it goes.  Thanks!

**Comment by stephencoe** [comment]
Just tested this and it works fine for both ways of setting the profile 👍

**Comment by stephencoe** [comment]
Hey @mmmorris1975, Happy new year!

do you think this fix might be merged soon ? :)

**Comment by mmmorris1975** [comment]
Thanks for reminding me @stephencoe, seems that this has been working so well that I forgot I actually needed to release this fix.  You can grab the released version of this fix at https://github.com/mmmorris1975/aws-runas/releases/tag/1.1.2

**Comment by stephencoe** [comment]
great thanks! 🌮
