### ISSUE TITLE
When using session-manager sending a ctrl+c causes unexpected behaviour

### ISSUE THREAD

**Issue by jfharden** [mmmorris1975/aws-runas#30]
Hello, when I ctrl+c while in an AWS Session Manager session which has been run with a single line aws-runas command, the macOS agent starts doing weird stuff and spits out both the remote command prompt and my local command prompt.

If I run it as
```
# aws-runas myaccount aws ssm start-session --target i-123456789`
```

when I ctrl+c it starts behaving badly, but if I

```
# $(aws-runas myaccount)
# aws ssm start-session --target i-123456789
```

then everything is fine.

I'm using:

-  iTerm2 3.2.7
- aws-runas 1.1.2
- session-manager-plugin 1.0.37.0
- macOS 10.13.6

There was originally a bug reported to the aws-ssm-agent project (https://github.com/aws/amazon-ssm-agent/issues/156) which displayed the same behaviour although wasn't using aws-runas, the suggestion there was it's about the handling of ctrl+c in the wrapping application (in our case aws-runas) which seems to be supported by my example usage above

**Comment by mmmorris1975** [comment]
Yep, this sure feels like a signal handling issue in aws-runas.  It's been something I've kept in the back of my mind to implement, but your use case is the first I've seen where the lack of proper signal handling is causing an issue.  I'll dig into this and make sure we do the right thing.

**Comment by mmmorris1975** [comment]
This has been release in version [1.2.1](https://github.com/mmmorris1975/aws-runas/releases/tag/1.2.1) feel free to give it a try and let me know if it behaves better for you.

The tool no longer directly handles the Interrupt (ctrl+c) and Quit (ctrl+\) signals, and will only forward those to the wrapped command.  To test this, I spun up a session-manager session and did those key sequences from the session-manager command prompt with no ill effect.

Also tested running the 'top' command inside the session and sent the same signals.  This stopped the execution of the 'top' command and dropped me back to the session-manager prompt.

**Comment by jfharden** [comment]
Just tried this out and it works a charm. Thanks so much for the quick fix, we use aws-runas all the time, thanks for the great work!
