### ISSUE TITLE
error- unexpected token `newline' /usr/local/bin/aws-runas: line 1: `<!DOCTYPE html>

### ISSUE THREAD

**Issue by imsuraj123** [mmmorris1975/aws-runas#34]
getting this eeror while running any aws runas commands 
/usr/local/bin/aws-runas: line 1: syntax error near unexpected token `newline'
/usr/local/bin/aws-runas: line 1: `<!DOCTYPE html>

**Comment by mmmorris1975** [comment]
Hello! Can you please tell me which version of aws-runas you are using? `aws-runas --version`

**Comment by mmmorris1975** [comment]
closed due to lack of response
