### ISSUE TITLE
Feature Request: Allow MFA token to be passed in via the command line

### ISSUE THREAD

**Issue by actionjack** [mmmorris1975/aws-runas#35]
Feature Request: Allow MFA token to be passed in via the command line
e.g. 

```bash
$ aws-runas --otp 000000
```

**Comment by mmmorris1975** [comment]
Great request!  I'm traveling for business this week, so I may be able to squeeze in a few hours at the airport to start digging in to this, shouldn't be a hard one.

**Comment by mmmorris1975** [comment]
This should be out as part of the 1.3.4 release.  Give it a try, and let me know how it works for you.  Thanks for the great suggestion.
