### ISSUE TITLE
version is blank when building from tar.gz (and others)

### ISSUE THREAD

**Issue by bram2000** [mmmorris1975/aws-runas#37]
Hello,
I've made a brew formula to make installing/updating aws-runas trivial on macos. During this process however, i've noticed a problem with the way the makefile passes the version into `go build`.

The version (VER) variable in the makefile is built using `git describe --tags`, but this returns a blank string if you are building from a release tarball (e.g. https://github.com/mmmorris1975/aws-runas/archive/1.3.4.tar.gz). This means that the version is never reported correctly when executing `aws-runas -V`.

Is there some other way the version could be injected?

**Comment by mmmorris1975** [comment]
I'm not familiar with building brew formula.  Is there any particular reason for that, other than just using the darwin build of the tool from the releases page?

**Comment by bram2000** [comment]
'Proper' brew formulae should build from source;

From the [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae) page:

> We don’t like binary formulae
> Our policy is that formulae in the core tap (homebrew/core) must be open-source with an OSI-approved license and either built from source or produce cross-platform binaries (e.g. Java, Mono). Binary-only formulae should go to homebrew/cask.

**Comment by mmmorris1975** [comment]
Thanks for the info!  I'll throw a few brain cells at it and find a way to make it so that it'll build from source without relying on the git tag data

**Comment by mmmorris1975** [comment]
I had to brush up on my 200-level Makefile usage, but I may have an easy-ish way for you to get what you're looking for.  You should be able to explicitly set the version when running your make command as part of the formula: `make VER=1.3.4` would build the binary with the Makefile's VER variable set to whatever you specify (in the example above 1.3.4), and not rely on the output of the git describe command.

As a quick test, I did a `brew create ...` and updated the install section to do:
```
system "make", "VER=#{version}"
```
and it behaved as I would have hoped, pulling in the auto-detected version from the GH url

**Comment by bram2000** [comment]
Thanks, got that working now.

The project does not het have enough reputation (stars/forks) to be allowed into `homebrew/core` but I have made it available on a custom tap, until such time that it is allowed. This means that installation on macos is now as simple as:

```
brew tap bram2000/custom
brew install aws-runas
```
Version updates in future can be handled gracefully via the standard brew mechanisms.

**Comment by mmmorris1975** [comment]
This is awesome!  Thanks so much for taking this up, and being a champion for it.  There really isn't any PR around the tool, so every star/fork have come completely organically.  I'll throw a line out to folks in my organization to see if I can help get that star count bumped up a bit
