### ISSUE TITLE
Add a command-line flag/subcommand to provide more info for saml roles

### ISSUE THREAD

**Issue by mmmorris1975** [mmmorris1975/aws-runas#50]
Decoding the SAMLResponse returned by IdPs is a pain during troubleshooting.  We already process it in order to allow the `-l` flag to work to list roles associated with a SAML enabled profile.  We should do something which will print the role ARN and principal ARN (maybe include RoleSessionName and SessionDuration too?) so that the info can be provided directly from the tool, and keep folks from having to base64 decode and eye-parse XML documents.

**Comment by timothyhutz** [comment]
I might do a feature branch to help you out with this. Are you just wanting the response data for a session token of an assumed role? Role name and Session timeout / duration left.

**Comment by mmmorris1975** [comment]
Hi Tim!  There's been a few times when troubleshooting with someone, we've had to take the raw SAMLResponse that's shown in the debug output and decode that to get inside to see what their IdP is passing to AWS for the Role and Principal ARNs.  I already have to do that in other parts of the code as part of the role assumption, my goal was to bring that forward so that people could get a better look at what's getting passed to AWS from their IdP.

I should have updated this ticket, but if you take a look at e5f219a I make an initial attempt at this.  Would be great to see what another set of eyes think about that implementation.

I'm interested to hear a bit more about the Session timeout/duration idea.  We have the `-e` flag, but that really only provides the info for the AWS credentials (AssumeRole for IAM and SAML, and SessionToken for IAM creds, if also given the `-s` flag)
