### ISSUE TITLE
AWSRUNAS_PROFILE no longer exported

### ISSUE THREAD

**Issue by mrflip** [mmmorris1975/aws-runas#66]
We use the `AWSRUNAS_PROFILE` environment variable that version 2.x emitted to determine which configuration files to draw on. That, as well as `AWS_SECURITY_TOKEN`, are no longer set by aws-runas.

How can I help restore the AWSRUNAS_PROFILE feature -- or is there some other way to find out which profile was chosen?

**Comment by mmmorris1975** [comment]
Let me get that fixed real quick.  Somehow I forgot to make sure those were available with the 3.x release

**Comment by mmmorris1975** [comment]
Version [3.1.2](https://github.com/mmmorris1975/aws-runas/releases/tag/3.1.2) should have this added back for you

https://github.com/mmmorris1975/aws-runas/releases/tag/3.1.2
