### ISSUE TITLE
add a --role_arn option to execute a one time command

### ISSUE THREAD

**Issue by beanderson** [mmmorris1975/aws-runas#7]
I want to be able to run a command as a different role without having to have an entry in my .aws/config

i.e. `aws-runas --role_arn arn:aws:iam::11223344:XXXX aws s3 ls`

**Comment by mmmorris1975** [comment]
Thanks for the great suggestion, I'll make it happen!

**Comment by mmmorris1975** [comment]
Will be release as 0.1.4 here shortly
