### ISSUE TITLE
/usr/local/bin/aws-runas  <profile> throwing error

### ISSUE THREAD

**Issue by mbsfernando** [mmmorris1975/aws-runas#70]
when try to run following command 
/usr/local/bin/aws-runas <profile>

it's throwing this error. 
2022/01/31 18:16:30 FATAL unable to determine SAML client from url

**Comment by mmmorris1975** [comment]
Hello!  This usually indicates some type of configuration issue.  Could you please run `/usr/local/bin/aws-runas -D <profile>` and show the output?  Feel free to redact semi-sensitive info like AWS account numbers, parts of the identity provider URL, or identity provider username, but leave enough data for me to get a general sense of the data in the output.

**Comment by mbsfernando** [comment]
here is the only output I see

$ aws-runas -D test-profile
2022/02/01 22:23:30 FATAL unable to determine SAML client from url

**Comment by everops-mikem** [comment]
Well, that's unfortunate!  Which identity provider are you using?  It may be a case where you'd need to explicitly configure the identity provider using the `saml_provider` attribute in the profile configuration.

**Comment by mmmorris1975** [comment]
That's unfortunate!  Which identity provider are you using to log in with?  It may be a case where you need to specify the `saml_provider` attribute in the profile configuration.

**Comment by mbsfernando** [comment]
saml_provider = azuread

this issue only appears when run the aws-runas  where bin file located in /usr/local/bin/aws-runas. if the bin run like ../folder/aws-runas then there is no issue.

**Comment by mmmorris1975** [comment]
That is certainly odd behavior.  Can you please provide the output for the following command:
```
aws-runas -v <profile> 2>&1 | head -6
```
Please run it twice, once where it doesn't work, and once when it does work.

This should give me a better look at what is happening before the tool starts communicating with AzureAD

**Comment by mmmorris1975** [comment]
Closed, no response
