### ISSUE TITLE
Unable to use rolearn instead of named profile on 3.3.0

### ISSUE THREAD

**Issue by cmcniel** [mmmorris1975/aws-runas#73]
Attempting to use aws-runas with a role arn instead of a named profile.   Client returns several errors related to retrys trying to connect to the local end-point after 3 attempts and then fails.

$ aws-runas  -E arn:aws:iam::<redacted>:role/<redacted>
2022/03/24 13:51:23 ERROR error calling GetCallerIdentity: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: operation error STS: GetSessionToken, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: connection refused
2022/03/24 13:51:56 operation error STS: AssumeRole, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: operation error STS: GetSessionToken, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: connection refused

Executing with the same with the -v flag exposes the following flow which repeats 2 times before ending.

2022/03/24 13:47:25 DEBUG using configuration source /Users/mcnicr/.aws/config
2022/03/24 13:47:25 DEBUG error loading configuration: section "profile arn:aws:iam::812653090533:role/PCMAdmin" does not exist
2022/03/24 13:47:25 DEBUG CLIENT CONFIG: &{CredentialsDuration:0s SessionTokenDuration:0s DurationSeconds:0 ExternalId: MfaSerial: MfaCode: MfaType:auto Region: RoleArn:arn:aws:iam::<redacted>:role/<role redacted> RoleSessionName: SrcProfile: JumpRoleArn:arn:aws:iam::<redacted>:role/<role redacted> SamlUrl: SamlUsername: SamlProvider: WebIdentityUrl: WebIdentityUsername: WebIdentityProvider: WebIdentityTokenFile: WebIdentityClientId: WebIdentityRedirectUri: FederatedUsername: ProfileName: sourceProfile:<nil>}
2022/03/24 13:47:25 DEBUG configuring Assume Role client
2022/03/24 13:47:25 DEBUG detected default or lower role credential duration, using session token credentials
2022/03/24 13:47:25 DEBUG configuring Session Token client
2022/03/24 13:47:25 DEBUG Detected expired or unset session token credentials, refreshing
2022/03/24 13:47:25 DEBUG provided duration less than 1, setting to default value
2022/03/24 13:47:38 DEBUG Detected expired or unset session token credentials, refreshing
2022/03/24 13:47:38 DEBUG provided duration less than 1, setting to default value
2022/03/24 13:47:46 DEBUG Detected expired or unset session token credentials, refreshing
2022/03/24 13:47:46 DEBUG provided duration less than 1, setting to default value
2022/03/24 13:47:55 ERROR error calling GetCallerIdentity: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: operation error STS: GetSessionToken, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: connection refused.

This use to work with the 2.3.2 client however since moving to AzureAD for IDP I have been using 3.3.0 which has this above behavior.

**Comment by mmmorris1975** [comment]
Using external IdPs with runas requires a little extra on the command line than with an IAM identity when using the role ARN vs. a named profile, because there is not enough information in the ARN to identify the IdP to contact.  Try adding the SAML URL needed to authenticate with AzureAD using the -S command line option.
```
aws-runas -vS https://azuread.com/my/endpoint arn:aws:iam::account:/role/my_role
```
It would also be advisable to use the -U option to provide the IdP username as well, but you'll be prompted if necessary. Alternatively, you could establish a session with the IdP using a named profile with authority to assume the role ARN(s) in question ahead of time.  Ideally you'll have the credentials for the IdP stored in the credentials file (aws-runas password --help), to avoid needing to provide them at runtime, but there's always the `-P` option if you want to specify them on the command line.

**Comment by cmcniel** [comment]
I had assumed the Idp and other parameters were being used from the 'default' profile when a profile wasn't being supplied.   In this case after setting the SAML_AUTH_URL and JUMP_ROLE_ARN both I was able to supply an arn for the role successfully.

**Comment by cmcniel** [comment]
I'm uncertain what problems using the defaults from the 'default' profile would cause.   Might be a nice feature in the future to reduce the number of parameters or environment variables required when using a raw arn.

**Comment by mmmorris1975** [comment]
Agreed, and I've found a way to make that happen.  It looks like the default profile data was not getting loaded when a role arn was passed instead of a named profile.  I'll be rolling out 3.3.1 here in the next day or 2 which should have this fix in it.
