### ISSUE TITLE
aws-runas creating and caching incorrect credentials when using serve ec2 or serve ecs

### ISSUE THREAD

**Issue by cmcniel** [mmmorris1975/aws-runas#76]
I have discovered that aws-runas is not correctly switching profiles from the web UI and subsequently creating and caching these incorrect credentials for use.

Included a pdf demonstrating this behavior where the web UI is used to switch profiles but, the credentials created and cached in the .aws/.aws_assume_role... files are for the initial profile selection.

[aws-runas-bug-3.x.pdf](https://github.com/mmmorris1975/aws-runas/files/8423542/aws-runas-bug-3.x.pdf)

**Comment by mmmorris1975** [comment]
I'm going to assume this was resolved as part of #79, which is addressed in [3.3.2](https://github.com/mmmorris1975/aws-runas/releases/tag/3.3.2)

If I'm mistaken, feel free to reopen this issue
