### ISSUE TITLE
aws runas 3.3.1 validation issue.

### ISSUE THREAD

**Issue by mhashendre** [mmmorris1975/aws-runas#80]
I use aws-runas 3.3.1 in windows 10. I encounter this validation issue. 

2022/04/20 10:23:15 DEBUG Detected expired or unset saml role credentials, refreshing
2022/04/20 10:23:16 operation error STS: AssumeRoleWithSAML, https response error StatusCode: 400, RequestID: a02e53a0-db50-464c-92bc-5011b14bd3cd, api error ValidationError: 4 validation errors detected: Value '' at 'roleArn' failed to satisfy constraint: Member must satisfy regular expression pattern: [\u0009\u000A\u000D\u0020-\u007E\u0085\u00A0-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]+; Value '' at 'roleArn' failed to satisfy constraint: Member must have length greater than or equal to 20; Value '' at 'principalArn' failed to satisfy constraint: Member must satisfy regular expression pattern: [\u0009\u000A\u000D\u0020-\u007E\u0085\u00A0-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]+; Value '' at 'principalArn' failed to satisfy constraint: Member must have length greater than or equal to 20.

Does anyone have a clue ?

**Comment by mmmorris1975** [comment]
Many times this indicates some sort of configuration issue.  In my experience it is usually an incorrect, or mis-typed, role ARN.  Can you run the command using the `-v` option, and post the output?  That will provide some more detail about the configuration to help debug the issue.

**Comment by mhashendre** [comment]
> Many times this indicates some sort of configuration issue. In my experience it is usually an incorrect, or mis-typed, role ARN. Can you run the command using the `-v` option, and post the output? That will provide some more detail about the configuration to help debug the issue.

The issue was resolved after removing the environmental variable AWS_PROFILE which is strange. I haven't defined this env variable. Anyways thanks for the reply.
