### ISSUE TITLE
Arm64 executable do not work post 3.3.0

### ISSUE THREAD

**Issue by vinodnsshivaram** [mmmorris1975/aws-runas#84]
looks like issue #67  is back again after 3.3.0 (3.3.3, 3.3.2 and 3.3.1 arm64 do not work, but works if i use amd64)

Device: 2021 16inch MacBook Pro - Apple M1 Pro
below errors when using 3.3.2

file aws-runas
aws-runas: Mach-O 64-bit executable arm64

./aws-runas
zsh: killed ./aws-runas

./aws-runas -D
zsh: killed ./aws-runas -D

./aws-runas -v
zsh: killed ./aws-runas -v

uname -a
Darwin ........ 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Comment by mmmorris1975** [comment]
I don't have an Apple ARM system to build (or validate the build output) with, so I need to rely on trying to cross compile from an x86 based Mac.  I've rebuilt the 3.3.3 binary, so see if it works.  If there's no change, there's not much else I'll be able to do on my own

**Comment by michailw** [comment]
Works fine for me. I had to allow Mac run this software in finder first (right-click menu -> open), to allow Mac run unverified software. Then in terminal it started work fine. Previously, result was the same as for @vinodnsshivaram

**Comment by mmmorris1975** [comment]
Thanks @michailw! I had to do the same thing on the new MBP I was issued for work.  Once I got past the MacOS "security" gates, I was able to run version 3.5.2 without issue
