### ISSUE TITLE
Segmentation fault: 11 in Mac OS 13.0 Ventura

### ISSUE THREAD

**Issue by ajity8** [mmmorris1975/aws-runas#91]
Hi, recently my Mac OS got updated to 13.0 and after that my aws-runas is not working with below error. 

`Segmentation fault: 11`

**Comment by mmmorris1975** [comment]
Hello Ajit!  The only mac system I have is company-manged and currently on 12.6 with no update available.  I won't be able to validate a build against 13 at this time.  I'll keep this issue open until I'm able to check out macOS 13 and get this addressed.  Unfortunately, I don't have a workaround for you, unless you are able to go back to macOS 12

**Comment by ajity8** [comment]
Thanks 👍.

For now, I'm exporting aws cloud shell access and token in the local shell as a workaround.

**Comment by AlexandrLi** [comment]
Also, have such an issue in Ventura. I will also use cloud shell for now. Thanks

**Comment by mmmorris1975** [comment]
My laptop was recently updated to Ventura and I've been able to resolve this.  It seems the upx tool, which I use to shrink the size of the compiled binary, doesn't play nice with the latest version of MacOS.  I've rebuilt the 3.5.0 release without using that tool, and I was able to create a working binary (at least on my Intel laptop, I'm unable to test ARM/M1 builds).

Please try the latest 3.5.0 build for darwin and let me know if it resolves this issue.

It appears this is a known issue with the upx tool (upx/upx#612)

**Comment by ajity8** [comment]
Thank you so much @mmmorris1975. It's working now 👍 . 

<img width="348" alt="image" src="https://user-images.githubusercontent.com/61748573/209441346-914afd55-eb73-40bd-8a25-4499ce408026.png">
