### ISSUE TITLE
Unable to download aws-runas-3.5.1-windows-amd64.zip

### ISSUE THREAD

**Issue by deekshakukreti** [mmmorris1975/aws-runas#98]
The file can't be downloaded due to security reasons. However, I am able to download other files compatible with Mac, Linux, etc. from the repo.

**Comment by mmmorris1975** [comment]
In the past, this issue has been related to anti-virus software incorrectly detecting the Windows download as malware.  Is there an anti-virus program on you system?  If it's Symantec, I used a process a while back which added a given version of aws-runas to their exemption list.  Another possibility could be that your system's or organization's security policy does not like the self-signed certificate used to sign the Windows executable.

**Comment by deekshakukreti** [comment]
It looks like the issue is local to my system, as it worked for other users. I am able to download it now. Thanks.
